apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexander-palmer
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: alexander-palmer
  template:
    metadata:
      labels:
        app: alexander-palmer
    spec:
      containers:
      - name: alexander-palmer
        image: gcr.io/enduring-piety/teamwebsite:latest
        ports: 
        - containerPort: 3000
        resources: 
          limits:
            cpu: 100m
            memory: 125M
          requests:
            cpu: 100m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata: 
  name: alex-pod-service
spec:
  selector:
      app: alex-palmer
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000