apiVersion: apps/v1
kind: Deployment
metadata:
  name: logan-bradford
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logan-bradford
  template:
    metadata:
      labels:
        app: logan-bradford
    spec:
      containers:
      - name: logan-bradford
        image: gcr.io/enduring-piety/Teamwebsite:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 100m
            memory: 250M
---
apiVersion: v1
kind: Service
metadata:
  name: logan-bradford-service
spec:
  selector:
    app: logan-bradford
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000