apiVersion: apps/v1
kind: Deployment
metadata:
  name: moses-mugarra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moses-mugarra
  template:
    metadata:
      labels:
        app: moses-mugarra
    spec:
      containers:
      - name: moses-mugarra
        image: gcr.io/enduring-piety/teamwebsite:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 100m
            memory: 250M
---
apiVersion: v1
kind: Service
metadata:
  name: moses-mugarra-service
spec:
  selector:
    app: moses-mugarra
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000